# Generated by Django 5.1.5 on 2025-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount_product_productcategory_delete_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
