# Generated by Django 5.1.5 on 2025-01-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='product discount'),
        ),
    ]
